# version: "3.9"

# services:

#   postgres:

#     image: postgres:17

#     environment:

#       POSTGRES_USER: admin

#       POSTGRES_PASSWORD: admin

#       POSTGRES_DB: pipeline

#     ports:

#       - "5432:5432"

#   pipeline:

#     build: .

#     depends_on:

#       - postgres

#     volumes:

#       - ./configs:/app/configs

#       - ./data:/app/data