- name: "csv_file"
  source_type: "file"
  config:
    file_path: "configs/data_source.xlsx"
    file_type: "excel"
    options: { "sheet_name": "data_source", "has_header": True }

- name: "postgresql"
  source_type: "database"
  config:
    engine: "postgresql"
    connection_info:
      database: "postgres"
      host: "localhost"
      port: 5432
      user: "postgres"
      password: "password"
    query: "SELECT * FROM table"
    options: null

- name: "test_opendb"
  source_type: "opendb"
  config:
    download_source_type: "ggdrive"
    des_path: "./data/0_staging"
    url: "https://drive.google.com/drive/folders/1lg6905H4ME_1ZFNTpFAREj8Bawa9zLnz"
    id: ""
    skip_existing: False
    dry_run: False
    options: { "item_type": "folder", "quiet": False }

- name: "google"
  source_type: "api"
  config:
    url: "https://google.com"
    method: "GET"
    options: null

- name: "yahoo"
  source_type: "api"
  config:
    url: "https://yahoo.com"
    method: "GET"
    options: null

- name: "bing"
  source_type: "api"
  config:
    url: "https://bing.com"
    method: "GET"
    options: null
